apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cloudconsolevibe-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/cpu-throttling: "false"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "20"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2000m"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/sessionAffinity: true
        run.googleapis.com/cpu-boost: true
    spec:
      serviceAccountName: cloud-console-vibe-sa@PROJECT_ID.iam.gserviceaccount.com
      containerConcurrency: 1000
      timeoutSeconds: 3600  # WebSocket support requires longer timeout
      containers:
      - image: gcr.io/PROJECT_ID/cloudconsolevibe-backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"

        - name: HOST
          value: "0.0.0.0"
        - name: FRONTEND_URL
          value: "https://cloud-console-vibe-HASH-uc.a.run.app"
        - name: DB_TYPE
          value: "sqlite"
        - name: METRICS_RETENTION_DAYS
          value: "30"
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        # Volume for persistent data (if needed)
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        emptyDir: {} 