steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'backend/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cloudconsolevibe-backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cloudconsolevibe-backend:latest'
      - 'backend/'
    
  # Push the backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/cloudconsolevibe-backend:$BUILD_ID'
      
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/cloudconsolevibe-backend:latest'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudconsolevibe-backend'
      - '--image=gcr.io/$PROJECT_ID/cloudconsolevibe-backend:$BUILD_ID'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--max-instances=20'
      - '--min-instances=1'
      - '--concurrency=1000'
      - '--timeout=3600'
      - '--session-affinity'
      - '--cpu-boost'
      - '--execution-environment=gen2'
      - '--set-env-vars=NODE_ENV=production,LOG_LEVEL=info,HOST=0.0.0.0'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/cloudconsolevibe-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/cloudconsolevibe-backend:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE' 